# Generated by Django 3.2.7 on 2021-10-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='direction',
            field=models.TextField(),
        ),
    ]
