# Generated by Django 3.2.7 on 2021-10-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_direction_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_units',
            field=models.CharField(choices=[('minutes', 'minutes'), ('hours', 'hours')], max_length=25),
        ),
    ]
