# Generated by Django 2.1.3 on 2018-11-14 15:26

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20181114_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipie',
            name='image',
            field=models.ImageField(default='static/site_img/default-image.jpg', upload_to=social.models._recipie_image_path),
        ),
    ]
