# Generated by Django 3.2.7 on 2021-10-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_recipe_cooking_time_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='prep_time_units',
            field=models.CharField(choices=[('minutes', 'minutes'), ('hours', 'hours')], max_length=20),
        ),
    ]
