# Generated by Django 2.1.3 on 2018-11-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20181114_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='cooking_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipie',
            name='equipment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipie',
            name='prep_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipie',
            name='serves',
            field=models.IntegerField(default=0),
        ),
    ]
