# Generated by Django 3.2.7 on 2021-10-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_recipe_prep_time_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_units',
            field=models.CharField(choices=[('minutes', 'minutes'), ('hours', 'hours')], default='minutes', max_length=25),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time_units',
            field=models.CharField(choices=[('minutes', 'minutes'), ('hours', 'hours')], default='minutes', max_length=20),
        ),
    ]
