# Generated by Django 3.2.7 on 2021-10-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_recimieuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='cooking_time_units',
            field=models.CharField(default='', max_length=20),
        ),
    ]
