# Generated by Django 3.2.7 on 2021-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('', ''), ('g', 'g'), ('kg', 'kg'), ('oz', 'oz'), ('lb', 'lb'), ('ml', 'ml'), ('l', 'l'), ('cup', 'cup'), ('cups', 'cups'), ('pinch', 'pinch'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('fl oz', 'fl oz'), ('pint', 'pint'), ('pints', 'pints'), ('quart', 'quart'), ('quarts', 'quarts'), ('gallon', 'gallon'), ('gallons', 'gallons'), ('whole', 'whole'), ('large', 'large'), ('small', 'small'), ('medium', 'medium'), ('sprinkle', 'sprinkle'), ('pinch', 'pinch'), ('dash', 'dash'), ('dollop', 'dollop'), ('dollops', 'dollops'), ('scoop', 'scoop'), ('scoops', 'scoops'), ('pieces', 'pieces'), ('piece', 'piece')], default='', max_length=20),
        ),
    ]
