# Generated by Django 3.2.7 on 2021-10-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_recipie_prep_time_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='content',
        ),
        migrations.AddField(
            model_name='recipie',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipie',
            name='method',
            field=models.TextField(default=''),
        ),
    ]
