# Generated by Django 3.2.7 on 2021-10-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20211013_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='ingredients',
        ),
    ]
