# Generated by Django 3.2.7 on 2021-10-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20211027_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(error_messages={'blank': 'Please enter the recipe name', 'null': 'Please enter the recipe name', 'required': 'Please enter the recipe name'}, max_length=255),
        ),
    ]
