# Generated by Django 3.2.7 on 2021-10-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='ingredient',
        ),
    ]
