# Generated by Django 3.2.7 on 2021-11-01 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[(' ', ' '), ('g', 'g'), ('kg', 'kg'), ('oz', 'oz'), ('lb', 'lb'), ('ml', 'ml'), ('l', 'l'), ('cup', 'cup'), ('cups', 'cups'), ('pinch', 'pinch'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('fl oz', 'fl oz'), ('pint', 'pint'), ('pints', 'pints'), ('quart', 'quart'), ('quarts', 'quarts'), ('gallon', 'gallon'), ('gallons', 'gallons'), ('whole', 'whole'), ('large', 'large'), ('small', 'small'), ('medium', 'medium'), ('sprinkle', 'sprinkle'), ('pinch', 'pinch'), ('dash', 'dash'), ('dollop', 'dollop'), ('dollops', 'dollops'), ('scoop', 'scoop'), ('scoops', 'scoops'), ('pieces', 'pieces'), ('piece', 'piece'), ('can', 'can'), ('cans', 'cans'), ('jar', 'jar'), ('jars', 'jars'), ('tin', 'tin'), ('tins', 'tins'), ('sheet', 'sheet'), ('sheets', 'sheets'), ('handful', 'handful'), ('handfuls', 'handfuls')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(error_messages={'blank': 'Please enter the recipe name', 'null': 'Please enter the recipe name', 'required': 'Please enter the recipe name'}, max_length=255, validators=[django.core.validators.MinLengthValidator(1, message='Please enter a recipe name.')]),
        ),
    ]
