# Generated by Django 3.2.7 on 2021-11-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_auto_20211101_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recimieuser',
            name='friends',
            field=models.ManyToManyField(null=True, to='social.RecimieUser'),
        ),
    ]
