# Generated by Django 3.2.7 on 2021-11-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_alter_recimieuser_friends'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recimieuser',
            managers=[
            ],
        ),
    ]
