# Generated by Django 3.2.7 on 2021-10-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_ingredient_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodstep', to='social.recipie')),
            ],
        ),
    ]
