# Generated by Django 3.2.7 on 2021-10-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_methodstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='method',
        ),
    ]
