# Generated by Django 3.2.7 on 2021-12-06 13:54

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('social', '0014_auto_20211206_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecimieUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('image', models.ImageField(null=True, upload_to=social.models._user_image_path)),
                ('description', models.TextField(blank=True)),
                ('friends', models.ManyToManyField(null=True, to='social.RecimieUser')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
