# Generated by Django 3.2.7 on 2021-12-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('social', '0017_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecimieUser',
        ),
    ]
