# Generated by Django 3.2.7 on 2021-12-10 13:51

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_delete_recimieuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=social.models._user_image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
